<?php

/**
 * @file
 * Contains va_gov_redirect_options.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function va_gov_redirect_options_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the va_gov_redirect_options module.
    case 'help.page.va_gov_redirect_options':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds options to redirects form') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function va_gov_redirect_options_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array('redirect-form', $form['#attributes']['class'])) {
    $vid = 'type_of_redirect';
    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
    foreach ($terms as $term) {
      $term_data[$term->name] = $term->name;
    }

    $form['redirect_type'] = [
      '#type' => 'select',
      '#title' => t('Select redirect type'),
      '#options' => $term_data,
    ];

    array_unshift($form['actions']['submit']['#submit'], 'va_gov_redirect_options_form_alter_submit');
  }
}

/**
 * Form callback.
 */
function va_gov_redirect_options_form_alter_submit(&$form, FormStateInterface $form_state) {
  $type = $form_state->getValue('redirect_type');

  $form_state->setValue(['redirect_redirect', '0', 'options'], ['type' => $type]);

  $path_raw = $form_state->getValue('redirect_source');
  $path = reset($path_raw)['path'];
  $type = $form_state->getValue('redirect_type');

  $db = \Drupal::database();
  $db->upsert('redirect_options')
    ->key(['source'])
    ->fields(['source' => $path, 'type' => $type])->execute();
}
